
package spdsr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SpDsrServices", targetNamespace = "http://webServices.dataInterface.thunisoft.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SpDsrServices {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllNDH", targetNamespace = "http://webServices.dataInterface.thunisoft.com/", className = "spdsr.GetAllNDH")
    @ResponseWrapper(localName = "getAllNDHResponse", targetNamespace = "http://webServices.dataInterface.thunisoft.com/", className = "spdsr.GetAllNDHResponse")
    public String getAllNDH();

    /**
     * 
     * @param ndh
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDataByNDH", targetNamespace = "http://webServices.dataInterface.thunisoft.com/", className = "spdsr.GetDataByNDH")
    @ResponseWrapper(localName = "getDataByNDHResponse", targetNamespace = "http://webServices.dataInterface.thunisoft.com/", className = "spdsr.GetDataByNDHResponse")
    public String getDataByNDH(
        @WebParam(name = "ndh", targetNamespace = "")
        Integer ndh);

}
