
package spdsr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SpDsrServicesImpl", targetNamespace = "http://webServices.dataInterface.thunisoft.com/", wsdlLocation = "http://11.203.54.130:8085/dataInterface/data/spdsr?wsdl")
public class SpDsrServicesImpl
    extends Service
{

    private final static URL SPDSRSERVICESIMPL_WSDL_LOCATION;
    private final static WebServiceException SPDSRSERVICESIMPL_EXCEPTION;
    private final static QName SPDSRSERVICESIMPL_QNAME = new QName("http://webServices.dataInterface.thunisoft.com/", "SpDsrServicesImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://11.203.54.130:8085/dataInterface/data/spdsr?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPDSRSERVICESIMPL_WSDL_LOCATION = url;
        SPDSRSERVICESIMPL_EXCEPTION = e;
    }

    public SpDsrServicesImpl() {
        super(__getWsdlLocation(), SPDSRSERVICESIMPL_QNAME);
    }

    public SpDsrServicesImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPDSRSERVICESIMPL_QNAME, features);
    }

    public SpDsrServicesImpl(URL wsdlLocation) {
        super(wsdlLocation, SPDSRSERVICESIMPL_QNAME);
    }

    public SpDsrServicesImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPDSRSERVICESIMPL_QNAME, features);
    }

    public SpDsrServicesImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpDsrServicesImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SpDsrServices
     */
    @WebEndpoint(name = "SpDsrServicesImplPort")
    public SpDsrServices getSpDsrServicesImplPort() {
        return super.getPort(new QName("http://webServices.dataInterface.thunisoft.com/", "SpDsrServicesImplPort"), SpDsrServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpDsrServices
     */
    @WebEndpoint(name = "SpDsrServicesImplPort")
    public SpDsrServices getSpDsrServicesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices.dataInterface.thunisoft.com/", "SpDsrServicesImplPort"), SpDsrServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPDSRSERVICESIMPL_EXCEPTION!= null) {
            throw SPDSRSERVICESIMPL_EXCEPTION;
        }
        return SPDSRSERVICESIMPL_WSDL_LOCATION;
    }

}
