
package szxajxx;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZxAjServices", targetNamespace = "http://webServices.dataInterface.thunisoft.com/", wsdlLocation = "http://11.203.54.130:8085/dataInterface/data/zxaj?wsdl")
public class ZxAjServices_Service
    extends Service
{

    private final static URL ZXAJSERVICES_WSDL_LOCATION;
    private final static WebServiceException ZXAJSERVICES_EXCEPTION;
    private final static QName ZXAJSERVICES_QNAME = new QName("http://webServices.dataInterface.thunisoft.com/", "ZxAjServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://11.203.54.130:8085/dataInterface/data/zxaj?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZXAJSERVICES_WSDL_LOCATION = url;
        ZXAJSERVICES_EXCEPTION = e;
    }

    public ZxAjServices_Service() {
        super(__getWsdlLocation(), ZXAJSERVICES_QNAME);
    }

    public ZxAjServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZXAJSERVICES_QNAME, features);
    }

    public ZxAjServices_Service(URL wsdlLocation) {
        super(wsdlLocation, ZXAJSERVICES_QNAME);
    }

    public ZxAjServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZXAJSERVICES_QNAME, features);
    }

    public ZxAjServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZxAjServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZxAjServices
     */
    @WebEndpoint(name = "ZxAjServicesImplPort")
    public ZxAjServices getZxAjServicesImplPort() {
        return super.getPort(new QName("http://webServices.dataInterface.thunisoft.com/", "ZxAjServicesImplPort"), ZxAjServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZxAjServices
     */
    @WebEndpoint(name = "ZxAjServicesImplPort")
    public ZxAjServices getZxAjServicesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices.dataInterface.thunisoft.com/", "ZxAjServicesImplPort"), ZxAjServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZXAJSERVICES_EXCEPTION!= null) {
            throw ZXAJSERVICES_EXCEPTION;
        }
        return ZXAJSERVICES_WSDL_LOCATION;
    }

}
