
package zxdsr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZxDsrServicesImpl", targetNamespace = "http://webServices.dataInterface.thunisoft.com/", wsdlLocation = "http://11.203.54.130:8085/dataInterface/data/zxdsr?wsdl")
public class ZxDsrServicesImpl
    extends Service
{

    private final static URL ZXDSRSERVICESIMPL_WSDL_LOCATION;
    private final static WebServiceException ZXDSRSERVICESIMPL_EXCEPTION;
    private final static QName ZXDSRSERVICESIMPL_QNAME = new QName("http://webServices.dataInterface.thunisoft.com/", "ZxDsrServicesImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://11.203.54.130:8085/dataInterface/data/zxdsr?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZXDSRSERVICESIMPL_WSDL_LOCATION = url;
        ZXDSRSERVICESIMPL_EXCEPTION = e;
    }

    public ZxDsrServicesImpl() {
        super(__getWsdlLocation(), ZXDSRSERVICESIMPL_QNAME);
    }

    public ZxDsrServicesImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZXDSRSERVICESIMPL_QNAME, features);
    }

    public ZxDsrServicesImpl(URL wsdlLocation) {
        super(wsdlLocation, ZXDSRSERVICESIMPL_QNAME);
    }

    public ZxDsrServicesImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZXDSRSERVICESIMPL_QNAME, features);
    }

    public ZxDsrServicesImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZxDsrServicesImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZxDsrServices
     */
    @WebEndpoint(name = "ZxDsrServicesImplPort")
    public ZxDsrServices getZxDsrServicesImplPort() {
        return super.getPort(new QName("http://webServices.dataInterface.thunisoft.com/", "ZxDsrServicesImplPort"), ZxDsrServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZxDsrServices
     */
    @WebEndpoint(name = "ZxDsrServicesImplPort")
    public ZxDsrServices getZxDsrServicesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices.dataInterface.thunisoft.com/", "ZxDsrServicesImplPort"), ZxDsrServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZXDSRSERVICESIMPL_EXCEPTION!= null) {
            throw ZXDSRSERVICESIMPL_EXCEPTION;
        }
        return ZXDSRSERVICESIMPL_WSDL_LOCATION;
    }

}
