
package zxkyc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZxKycServices", targetNamespace = "http://webServices.dataInterface.thunisoft.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZxKycServices {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSANH", targetNamespace = "http://webServices.dataInterface.thunisoft.com/", className = "zxkyc.GetAllSANH")
    @ResponseWrapper(localName = "getAllSANHResponse", targetNamespace = "http://webServices.dataInterface.thunisoft.com/", className = "zxkyc.GetAllSANHResponse")
    public String getAllSANH();

    /**
     * 
     * @param sanh
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDataByNDH", targetNamespace = "http://webServices.dataInterface.thunisoft.com/", className = "zxkyc.GetDataByNDH")
    @ResponseWrapper(localName = "getDataByNDHResponse", targetNamespace = "http://webServices.dataInterface.thunisoft.com/", className = "zxkyc.GetDataByNDHResponse")
    public String getDataByNDH(
        @WebParam(name = "sanh", targetNamespace = "")
        String sanh);

    /**
     * 
     * @param sanh
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDataBySANH", targetNamespace = "http://webServices.dataInterface.thunisoft.com/", className = "zxkyc.GetDataBySANH")
    @ResponseWrapper(localName = "getDataBySANHResponse", targetNamespace = "http://webServices.dataInterface.thunisoft.com/", className = "zxkyc.GetDataBySANHResponse")
    public String getDataBySANH(
        @WebParam(name = "sanh", targetNamespace = "")
        String sanh);

}
