
package zxkyc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZxKycServices", targetNamespace = "http://webServices.dataInterface.thunisoft.com/", wsdlLocation = "http://11.203.54.130:8085/dataInterface/data/zxkyc?wsdl")
public class ZxKycServices_Service
    extends Service
{

    private final static URL ZXKYCSERVICES_WSDL_LOCATION;
    private final static WebServiceException ZXKYCSERVICES_EXCEPTION;
    private final static QName ZXKYCSERVICES_QNAME = new QName("http://webServices.dataInterface.thunisoft.com/", "ZxKycServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://11.203.54.130:8085/dataInterface/data/zxkyc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZXKYCSERVICES_WSDL_LOCATION = url;
        ZXKYCSERVICES_EXCEPTION = e;
    }

    public ZxKycServices_Service() {
        super(__getWsdlLocation(), ZXKYCSERVICES_QNAME);
    }

    public ZxKycServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZXKYCSERVICES_QNAME, features);
    }

    public ZxKycServices_Service(URL wsdlLocation) {
        super(wsdlLocation, ZXKYCSERVICES_QNAME);
    }

    public ZxKycServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZXKYCSERVICES_QNAME, features);
    }

    public ZxKycServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZxKycServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZxKycServices
     */
    @WebEndpoint(name = "ZxKycServicesImplPort")
    public ZxKycServices getZxKycServicesImplPort() {
        return super.getPort(new QName("http://webServices.dataInterface.thunisoft.com/", "ZxKycServicesImplPort"), ZxKycServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZxKycServices
     */
    @WebEndpoint(name = "ZxKycServicesImplPort")
    public ZxKycServices getZxKycServicesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices.dataInterface.thunisoft.com/", "ZxKycServicesImplPort"), ZxKycServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZXKYCSERVICES_EXCEPTION!= null) {
            throw ZXKYCSERVICES_EXCEPTION;
        }
        return ZXKYCSERVICES_WSDL_LOCATION;
    }

}
